// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChitChatClients_GetClients_FullMethodName = "/ChitChatClients/GetClients"
)

// ChitChatClientsClient is the client API for ChitChatClients service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChitChatClientsClient interface {
	GetClients(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Clients, error)
}

type chitChatClientsClient struct {
	cc grpc.ClientConnInterface
}

func NewChitChatClientsClient(cc grpc.ClientConnInterface) ChitChatClientsClient {
	return &chitChatClientsClient{cc}
}

func (c *chitChatClientsClient) GetClients(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Clients, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Clients)
	err := c.cc.Invoke(ctx, ChitChatClients_GetClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChitChatClientsServer is the server API for ChitChatClients service.
// All implementations must embed UnimplementedChitChatClientsServer
// for forward compatibility.
type ChitChatClientsServer interface {
	GetClients(context.Context, *Empty) (*Clients, error)
	mustEmbedUnimplementedChitChatClientsServer()
}

// UnimplementedChitChatClientsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitChatClientsServer struct{}

func (UnimplementedChitChatClientsServer) GetClients(context.Context, *Empty) (*Clients, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClients not implemented")
}
func (UnimplementedChitChatClientsServer) mustEmbedUnimplementedChitChatClientsServer() {}
func (UnimplementedChitChatClientsServer) testEmbeddedByValue()                         {}

// UnsafeChitChatClientsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitChatClientsServer will
// result in compilation errors.
type UnsafeChitChatClientsServer interface {
	mustEmbedUnimplementedChitChatClientsServer()
}

func RegisterChitChatClientsServer(s grpc.ServiceRegistrar, srv ChitChatClientsServer) {
	// If the following call pancis, it indicates UnimplementedChitChatClientsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChitChatClients_ServiceDesc, srv)
}

func _ChitChatClients_GetClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitChatClientsServer).GetClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChitChatClients_GetClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitChatClientsServer).GetClients(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ChitChatClients_ServiceDesc is the grpc.ServiceDesc for ChitChatClients service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChitChatClients_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChitChatClients",
	HandlerType: (*ChitChatClientsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClients",
			Handler:    _ChitChatClients_GetClients_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
